/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.wydryszekWojciech.m09.cryptoutil;

class LibraryTest {
    /*
    @Test void someLibraryMethodReturnsTrue() {
        cryptoUtils classUnderTest = new cryptoUtils();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    */


}
