/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.wydryszekWojciech.m09;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    /*
    @Test void someLibraryMethodReturnsTrue() {
        cryptoUtils classUnderTest = new cryptoUtils();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    */


}
